### PR TITLE
chore: replace @types/is-stream with correct @types/isstream

### PR DESCRIPTION
**Pull request by MasterOdin**
This changes the installed `@types` file to use the right typing package for the isstream module that is depended upon concretely.

##### Checklist

- [x] `npm test` passes (tip: `npm run lint-fix` can correct most style issues)

### CODE REVIEW

**Comment by MasterOdin** [comment]
It seems like `file-type` is also missing from the `types` array in the tsconfig.json, though I've never used it so I'm not sure if that was on purpose or not.

**Comment by dpopp07** [comment]
I didn't do that on purpose, so if you think it would be useful feel free to add it

**Comment by MasterOdin** [comment]
Would it also make sense to just remove the key and let `tsc` automatically find the necessary types it needs automatically from the `node_modules/@types/` directory?

**Comment by dpopp07** [comment]
If TypeScript does that, yeah that sounds good to me

**Comment by MasterOdin** [comment]
Sounds good, I've commented out that bit of code.

**Pull request merged**
