### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by kenime**
Executed `npm test` and all passed.

### CODE REVIEW

**Comment by kenime** [comment]
summary of changes: executed npm audit fix and updated axios library to 0.19.0.

**Comment by dpopp07** [comment]
@kenime Thanks for the PR, but we do not want to update `axios` to 0.19 at this time. According to [all of the issues in their repo](https://github.com/axios/axios/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+0.19), there are many breaking changes associated with the release that I don't want to introduce.

**Comment by kenime** [comment]
Got it. The reason I updated axios is because it fixed an issue when using
http proxy with https URLs.

**Comment by dpopp07** [comment]
Yeah, `axios` has some issues when using proxies. Some of those issues are still present in 0.19 as well, I've done some testing there.

Have you tried looking at [this workaround](https://github.com/watson-developer-cloud/node-sdk#using-the-sdk-behind-a-corporate-proxy)? That should work with `axios` 0.18.

**Comment by kenime** [comment]
I tried axios@0.19.0-beta and proxy worked fine.

Interesting trick, the thing is I am using node-red-node-watson (Node Red
wrapper on watson-developer-cloud), so I couldnt directly apply this trick.

Anyway, agree that it is not a good moment for this PR.

**Comment by dpopp07** [comment]
Sounds good. If you want to amend the PR to just update the other dependencies, I will review that. Also, make sure you sign the CLA

**Comment by dpopp07** [comment]
Closing as some dependencies have been updated separately

**Pull request closed without merging**
