### PR TITLE
fix(auth): migrate to secure usage of jwt for token authentication

### PR DESCRIPTION
**Pull request by dpopp07**
There is a vulnerability in v8 of the `jsonwebtoken` dependency. This commit upgrades to v9 to resolve the vulnerability. Additionally, they made an effort in this version to discourage the less secure "decode" method in favor of the more secure "verify" method. This commit also refactors the code and tests to use the "verify" method.

### CODE REVIEW

**Comment by TannerS** [comment]
Thanks for this, please let us know an update, i think a lot of us have a short deadline to get this fixed, and this is a dep of another dep

**Review by apaparazzi0329 — APPROVED** [review]
There were no issues authenticating in the node sdk and the code looks good so you got my approval

**Review by padamstx — APPROVED** [review]
LGTM

**Pull request merged**
