### PR TITLE
chore: update pkglock.json

### PR DESCRIPTION
**Pull request by christiancompton**
This PR updates the package-lock.json to address a disclosed vulnerability in a transitive dependency.

### CODE REVIEW

**Review by dpopp07 — APPROVED** [review]
This is difficult to review but it seems fine and the tests are all passing, so it looks okay to me 👍

**Comment by padamstx** [comment]
I took a glance at the changes after seeing @dpopp07 's comment, and I think the file changed so much due to @christiancompton using an older version of npm.
I think Dustin and I are using npm v7 which uses the lockfile v2 if I understand things correctly.

**Comment by dpopp07** [comment]
You may be right, though I moved back to npm v6 a while ago because I was having issues with v7

**Pull request merged**
