### PR TITLE
build: update vulnerable dependencies

### PR DESCRIPTION
**Pull request by barrett-schonefeld**
I updated to the latest version of `Jest`, which removes the dependency on `set-value`.

### CODE REVIEW

**Comment by padamstx** [comment]
@barrett-schonefeld The [two dependabot alerts](https://github.com/IBM/node-sdk-core/security/dependabot) that we're seeing in the node core indicate that the following dependency upgrades need to be made:
1. semver-regex  >=3.1.3  (there's actually a PR open for this change)
2. set-value >=4.0.1 (that would be a major version change, so not sure if that would break anything).

I don't think your proposed changes address either of those, do they?   In fact, I'm not really seeing any version # changes at all... looks like the only changes are the removal of the "bundled" lines from package-lock.json.

I'll go ahead and merge in the semver-regex-related PR that was opened up by dependabot automatically, as that will at least address one of the vulnerabilities.

**Comment by barrett-schonefeld** [comment]
> I don't think your proposed changes address either of those, do they?

Not initially, but now I updated `Jest` to the latest, which removes `set-value` as a dependency.

> I'll go ahead and merge in the semver-regex-related PR that was opened up by dependabot automatically, as that will at least address one of the vulnerabilities.

I rebased after you merged the `semver-regex` work, so both vulnerabilities should be resolved.

**Comment by barrett-schonefeld** [comment]
> Not initially, but now I updated `Jest` to the latest, which removes `set-value` as a dependency.

I need to update some of the tests to work with the latest version of `Jest`.

**Comment by barrett-schonefeld** [comment]
Removed the use of done in async tests because `Jest@27` does not allow tests to both utilize `done` and return a promise.

For more information on this change, see this [Jest issue](https://github.com/facebook/jest/issues/10529).

**Review by padamstx — APPROVED** [review]
LGTM

**Review by dpopp07 — APPROVED** [review]
Looks good! Thanks for doing this, Barrett. Glad to finally be rid of the redundant `done()` calls 🙂

**Pull request merged**
